apiVersion: v1
kind: Service
metadata:
  labels:
    app: vidgenapi
  name: vidgenapi
  namespace: video-creator
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: vidgenapi
